#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
#colorscheme = "desert"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true 
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"

statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
enable_neomake = false
enable_ale = false
filemanager = "defx"
bootstrap_before = "myspacevim#before"
defalut_indent = 4
expand_tab = false

[[custom_plugins]]
name = "CodeFalling/fcitx-vim-osx"
merged = false
loadconf = true
[[custom_plugins]]
name = "rking/ag.vim"
merged = false
loadconf = true

[[layers]]
name = "ctrlp"

[[layers]]
name = "default"

[[layers]]
name = "tools"

[[layers]]
name = "git"

[[layers]]
name = "checkers"
show_cursor_error = false
enable = false

[[layers]]
name = "tmux"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#markdown"
